// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vdpksydkiyziywwmfrwg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkcGtzeWRraXl6aXl3d21mcndnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNzM1MTcsImV4cCI6MjA3Mzg0OTUxN30.KOJizS9m4gxsWGVYT9IZa5mxRNna6gvtj8tgbuMy8u8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});